services:
  Konseria:
    image: php:apache
    container_name: konseria_71220822
    ports:
      - 80:80
    volumes:
      - ./progweb:/var/www/html
    networks:
      - mahasiswa
    env_file:
      - stack.env


networks:
  mahasiswa:
    external : true
    name: dba_mahasiswa